name: force-push

on:
  push:
    branches:
      - main
      - staging
      - dev
    paths:
      - 'src/pkgs/*/interface/**'
      - 'compile_interfaces.sh'

env:
  FOUNDRY_PROFILE: ci

jobs:
  force-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive' # instead of 'true' in case interfaces need to be built
      - name: compiles interfaces
        run: ./compile_interfaces.sh
      - name: force-push to interfaces repo
        id: direct-push
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: ${{ secrets.WORKFLOW_DEPLOY_KEY }}
        with:
          source-directory: tmp/interfaces
          target-directory: 'src/interfaces'
          destination-github-username: 'DhairyaSethi'
          destination-repository-name: 'tmp-interfaces'
          commit-message: upd(${{ github.event.head_commit.message || github.event.workflow_run.head_commit.message }}) pushed from $GITHUB_REF
          user-email: me@derl.com
          target-branch: ${{ github.head_ref || github.ref_name }}
